"""Update schema

Revision ID: 42ab90c889d9
Revises: 2a8157226361
Create Date: 2026-09-19 20:12:37.889707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42ab90c889d9'
down_revision: Union[str, Sequence[str], None] = '2a8157226361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('items', sa.Column('text_payload', sa.Text(), nullable=True))
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('items', 'content')
    op.drop_column('items', 'file_type')
    op.drop_column('items', 'file_size')
    op.drop_column('items', 'item_type')
    op.drop_column('items', 'title')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('items', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('items', 'text_payload')
    op.drop_column('items', 'content_type')
    # ### end Alembic commands ###
