"""add file_size to items

Revision ID: b6aa9d88c2bf
Revises: 42ab90c889d9
Create Date: 2026-09-22 17:21:33.851878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aa9d88c2bf'
down_revision: Union[str, Sequence[str], None] = '42ab90c889d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'file_size')
    # ### end Alembic commands ###
